services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: python3 -m cte_ai
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: node .output/server/index.mjs
    ports:
      - "3000:3000"
    restart: always
